### ISSUE TITLE
The FrobMeister exits early with only one --frob

### ISSUE THREAD

**Issue by lars-t-hansen** [bnjbvr/cretonne#4]
The FrobMeister exits early unless the --frob option is used at least twice. 

- What are the steps to reproduce the issue? Can you include a CLIF test case,
  ideally reduced with the `bugpoint` clif-util command?

Run `clif-util --frob`, supplying the option exactly once.

- What do you expect to happen? What does actually happen? Does it panic, and
  if so, with which assertion?

It should print "Frobbing now... done".  Instead it prints "NO FROBBING" and then segfaults.  If you supply "--frob" at least twice it seems to work OK.

- Which Cranelift version / commit hash / branch are you using?

On trunk.

- If relevant, can you include some extra information about your environment?
  (Rust version, operating system, architecture...)

Fedora core 30, x64.

**Comment by bnjbvr** [comment]
It's not a big, it's a feature: in your example, no actual command was passed to clif-util, so the FrobMeister doesn't know what to frob.
